- src/data/cache.ts
- src/utils/cache.ts
Was accidentally commented out
> Reimplement cache version checking

- package.json
- src/config.ts
- src/elements/common/file-uploader.ts
- src/elements/dev/cdn-sites.ts
- src/elements/dev/version/version-info-identity.ts
- src/elements/identity/identity-profile-edit.ts
- src/elements/pages/dev/game/settings/game-settings-general.ts
- src/elements/pages/dev/group/settings/group-settings-general.ts
- src/elements/root/ui-root.ts
- src/ui/helpers.ts
- src/utils/global.ts
- src/utils/utils.ts
- yarn.lock
- WIP ipml bootstrapping step
- Update upload api calls
- Fix status
- Remove use of IS_PROD
> Bootstrap endpoint, dynamic Turnstyle keys

- src/elements/root/ui-root.ts
> chore: remove debug on prod

- package.json
- src/elements/overlay/register-panel.ts
- src/elements/root/ui-root.ts
- yarn.lock
- Don't show auth if no captcha, captcha as a future
- fmt
> Don't show captcha if captcha not configured on backend

- src/config.ts
- webpack.common.js
Automatically determine the API endpoint for deployments to custom clusters instead of hardcoding production
> Automatically determine API endpoint

- src/data/assets.ts
- src/elements/common/rvt-nav.ts
- src/elements/dev/dev-game-tile.ts
- src/elements/pages/dev/device-link.ts
- src/elements/pages/dev/game/game-banner.ts
- src/elements/pages/dev/game/rvt-user-games.scss
- src/elements/pages/dev/game/rvt-user-games.ts
- src/elements/pages/dev/group/group-banner.ts
- src/elements/pages/dev/group/group.scss
- src/elements/pages/dev/group/group.ts
- src/elements/pages/link-game.ts
Updated gradients to improve contrast
Added new create-game icon
> feat(hub-201) - Migrate logos to SVGs, fix icon scaling

- src/elements/overlay/alert-panel.scss
- src/elements/pages/dev/game/rvt-user-games.ts
- src/elements/root/rvt-root.ts
- src/utils/global.ts
> feat(HUB-183): adds bootstrap error message

- package.json
- src/elements/common/rvt-nav.ts
- src/elements/overlay/register-panel.ts
- src/elements/pages/access-token.scss
- src/elements/pages/access-token.ts
- src/elements/pages/dev/game/rvt-user-games.ts
- src/elements/pages/module.ts
- src/elements/pages/rvt-user-consent.ts
- src/elements/pages/rvt-user-dashboard.ts
- src/elements/root/rvt-root.ts
- src/elements/root/rvt-router.ts
- src/routes.ts
- src/utils/error-signals.ts
- src/utils/global.ts
- yarn.lock
Related: https://github.com/rivet-gg/rivet/pull/177
- Added admin login page
- Added instructions for admin login when on an OSS backend
> Implement admin login page

- .github/workflows/license-check.yaml
- .gitignore
- package.json
- src/hub.ts
- src/static-site.ts
- src/utils/start-monitoring.ts
- src/utils/start-posthog.ts
- webpack.prod.js
- yarn.lock
> Integrate Sentry

- src/routes.ts
> Fix prvt-game-dashboard typo

- src/utils/global.ts
See https://github.com/fern-api/fern/pull/2553
> Remove x-fern-* headers for cors policy

- package.json
- scripts/copy-api-ee.sh
- src/elements/pages/analytics/chart.scss
- src/elements/pages/analytics/chart.ts
- src/elements/pages/analytics/configs.ts
- src/elements/pages/analytics/module.ts
- src/elements/pages/analytics/overview.scss
- src/elements/pages/analytics/overview.ts
- vendor/rivet-gg-api-ee.tgz
- yarn.lock
Not intended to be launched publicly yet, but it can be accessed if you know the URL.
> Analytics overview re-enabled

- src/elements/layouts/page-header.scss
- src/elements/pages/analytics/chart.scss
- src/elements/pages/analytics/chart.ts
- src/elements/pages/analytics/module.ts
- src/elements/pages/analytics/overview.ts
- src/elements/pages/analytics/rvt-game-analytics.ts
- src/elements/pages/analytics/utilities.ts
- src/elements/pages/dev/game/pages/game-overview.ts
> Analytics widget

- src/elements/root/rvt-root.ts
> Bootstrap error formatting

- src/elements/pages/analytics/chart.ts
- src/elements/pages/rvt-user-consent.ts
> Remove whitelist info

- src/elements/common/overlay-positioning.scss
- src/elements/common/overlay-positioning.ts
- src/elements/dev/drop-down-list.scss
- tailwind.config.js
> fix(HUB-237): fixes how `drop-down-list` is displayed

- shell.nix
- src/elements/common/toggle-switch.ts
- src/elements/pages/dev/namespace/rvt-namespace-settings.scss
- src/elements/pages/dev/namespace/rvt-namespace-settings.ts
Fixes RVT-3536
The underlying functionality just sets the max count to the max value of i32 (2 ^ 31 - 1) when disabled.
> Add toggle switch to max players

- src/elements/pages/dev/game/pages/game-logs.ts
Merge with https://github.com/rivet-gg/site/pull/73
> Add memory info bubble

- src/elements/common/rvt-namespace-dropdown.ts
> Hide scrollbars if there's nothing to scroll

- src/elements/common/rvt-breadcrumbs.ts
- src/routes.ts
> Add missing titles in breadrumbs for Analytics and Profile Settings

- package.json
- shell.nix
- src/elements/common/button/rvt-button.styles.ts
- src/elements/common/button/rvt-button.ts
- src/elements/common/rvt-copy-area.ts
- src/elements/overlay/register-panel.scss
- src/elements/overlay/register-panel.ts
- src/elements/pages/access-token.ts
- src/elements/pages/dev/user/settings.ts
- src/elements/pages/rvt-user-consent.ts
- src/elements/profile/user-banner.ts
- src/elements/root/rvt-root.ts
- src/utils/api.ts
- src/utils/auth.ts
- src/utils/global.ts
- yarn.lock
> Fix admin login, make login/logout not refresh page

- src/elements/dev/text-input.scss
- src/elements/dev/text-input.ts
- src/elements/pages/dev/game/pages/game-overview.ts
- src/elements/pages/dev/game/settings/game-settings-general.ts
> Fix create namespace error

- src/elements/pages/dev/game/pages/game-logs.ts
Merge with https://github.com/rivet-gg/site/pull/140
> Fix montioring docs link

- src/elements/common/button/rvt-button.styles.ts
- src/elements/common/button/rvt-button.ts
- src/elements/dev/dev-game-logs-sidebar.ts
- src/elements/pages/dev/game/pages/game-logs.scss
- src/elements/pages/dev/game/pages/game-logs.ts
- src/utils/emoji.ts
- tailwind.config.js
Went the extra mile with this and:
- updated some styles to match the design
- added flags here:
- added flags here also:
- added an icon for "failed" lobbies:
- added an icon for "not-started" lobbies (yes, it's spinning):
Closes HUB-272
> Adds country flag in the logs viewer

- src/elements/overlay/alert-panel.scss
- src/elements/overlay/alert-panel.ts
- src/elements/pages/dev/game/rvt-user-games.ts
- src/elements/pages/dev/game/settings/game-settings-billing.ts
fixes HUB-366 HUB-370 HUB-367 HUB-368 HUB-369 HUB-372 HUB-376
> feat(HUB-370): new design for billing page

- src/config.ts
> fix: hide devtools from prod

- src/elements/pages/analytics/chart.ts
- vendor/rivet-gg-api-ee.tgz
- yarn.lock
**DO NOT MERGE BEFORE** https://app.graphite.dev/github/pr/rivet-gg/rivet-ee/23/Fix-staggered-graphs-bug
Fixes RVT-3578
> Fix staggered graphs bug

- package.json
- src/elements/dev/text-input.ts
- src/elements/pages/dev/game/rvt-user-games.ts
- src/utils/api.ts
- yarn.lock
**MERGE WITH** https://app.graphite.dev/github/pr/rivet-gg/rivet/461/Auto-generate-name-id-for-games
> Remove name id from game creation

- src/elements/common/button/rvt-button.styles.ts
- src/utils/identify-user.ts
> fix: invalid buttons styling and crashing posthog

- package.json
- scripts/copy-api-ee.sh
- src/elements/dev/dev-game-logs-sidebar.ts
- src/elements/pages/dev/game/pages/game-lobbies.ts
- src/elements/pages/dev/game/pages/game-logs.ts
- src/elements/pages/dev/game/settings/game-settings-billing.ts
- src/utils/emoji.ts
- yarn.lock
Do not merge until https://github.com/rivet-gg/rivet/pull/300 is deployed
> fix: update to use region name id

- src/elements/pages/dev/game/rvt-user-games.ts
> feat(HUB-382): remove billing button from homepage

- src/elements/common/rvt-namespace-dropdown.ts
- src/elements/root/rvt-router.ts
> fix(HUB-229): merge url params when switching namespaces 

- apps/hub/src/domains/game/components/game-backend/game-backend-call-details.tsx
- apps/hub/src/queries/watch.ts
- packages/components/src/ui/input.tsx
> fix: minor tweaks

- apps/hub/src/domains/game/views/game-namespaces.tsx
- packages/components/src/ui/typography.tsx
> feat(HUB-400): display name id in the namespaces list

- apps/hub/src/components/dialogs/feedback-dialog.tsx
- apps/hub/src/routes/__root.tsx
- apps/hub/src/routes/_authenticated/_layout/index.tsx
Allows to pass utm_source parameter to Posthog's survey.
> feat: add utm to feedback form

- apps/hub/src/domains/game/queries/mutations.ts
- apps/hub/src/routes/__root.tsx
- apps/hub/src/routes/_authenticated/_layout/index.tsx
> Game creation fixes

- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/namespaces/$namespaceId.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/namespaces/$namespaceId/cdn.tsx
> feat(HUB-427): add missing namespaceNameId to cdn configuration

- apps/hub/src/domains/game/components/game-backend/game-backend-event-summary-logs.tsx
- apps/hub/src/domains/game/components/game-backend/game-backend-event-summary.tsx
- apps/hub/src/domains/game/queries/backend/types.ts
- apps/hub/src/layouts/root.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId/backend/$environmentId/logs.tsx
- packages/components/public/theme.css
- packages/components/src/logs-select.tsx
- packages/components/src/logs-view.tsx
- packages/components/src/ui/button.tsx
> feat(HUB-413): add exceptions view to opengb logs

- apps/hub/src/domains/auth/contexts/auth.tsx
- apps/hub/src/domains/user/queries/query-options.ts
- apps/hub/src/queries/global.ts
> fix(HUB-410): robust auth

- apps/hub/src/domains/group/components/dialogs/confirm-leave-group-dialog.tsx
- apps/hub/src/domains/group/queries/mutations.ts
- apps/hub/src/domains/group/views/group-members.tsx
- apps/hub/src/hooks/use-dialog.tsx
- apps/hub/src/routes/_authenticated/_layout/teams/$groupId.tsx
> feat(HUB-411): leave group

- apps/hub/src/routeTree.gen.ts
- apps/hub/src/routes/_authenticated/billing.tsx
- packages/components/src/ui/button.tsx
- packages/components/src/ui/card.tsx
> feat(HUB-437): standalone billing page

- apps/hub/src/domains/group/queries/mutations.ts
- apps/hub/src/lib/utils.ts
- apps/hub/src/queries/global.ts
- apps/hub/src/routes/_authenticated/invite.$inviteCode.tsx
> feat(HUB-403): handle invite errors

- apps/hub/src/domains/group/views/group-list-view.tsx
> fix(HUB-436): hide create team button if not admin

- apps/hub/src/routeTree.gen.ts
- apps/hub/src/routes/_authenticated/access-token.$token.tsx
> feat(HUB-401): add access token page for cli login

- apps/hub/src/domains/game/forms/backend-env-create-form.tsx
- apps/hub/src/domains/game/forms/group-create-game-form.tsx
- apps/hub/src/domains/game/forms/namespace-create-form.tsx
- apps/hub/src/domains/group/components/group-create-card.tsx
- apps/hub/src/domains/group/components/no-groups-alert.tsx
- apps/hub/src/domains/group/forms/group-create-form.tsx
- apps/hub/src/domains/group/views/group-list-view.tsx
- apps/hub/src/domains/user/queries/mutations.ts
- apps/hub/src/lib/async-validation.ts
- apps/hub/src/queries/global.ts
- apps/hub/src/routes/_authenticated/_layout/index.tsx
> fix(RVTEE-339): new accounts can't create new groups

- apps/hub/src/domains/auth/views/login-view/hooks.ts
- apps/hub/src/queries/global.ts
- apps/hub/src/queries/watch.ts
> fix: issues with login

- apps/hub/src/domains/game/components/game-servers/game-server-runtime-tab.tsx
- apps/hub/src/domains/game/components/game-servers/game-server-tags.tsx
- apps/hub/src/domains/game/queries/dynamic-servers/mutations.ts
- apps/hub/src/domains/game/queries/dynamic-servers/query-options.ts
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/servers/builds.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/servers/index.tsx
- yarn.lock
> feat: current/latest in build list

- apps/hub/src/domains/game/components/game-backend/game-backend-environment-database-link.tsx
- apps/hub/src/domains/game/helpers/get-or-create-backend-project.ts
- apps/hub/src/domains/game/helpers/try-create-backend.ts
- apps/hub/src/domains/game/queries/dynamic-servers/query-options.ts
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/backend.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/index.tsx
> feat add new cards to env overview

- apps/hub/src/domains/game/components/game-servers/game-servers-list-panel.tsx
- apps/hub/src/domains/game/components/game-servers/game-servers-list-preview.tsx
- apps/hub/src/domains/game/helpers/try-create-backend.ts
- apps/hub/src/domains/game/queries/dynamic-servers/query-options.ts
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/servers/index.tsx
> feat: add pagination to servers list

- apps/hub/src/domains/group/components/dialogs/create-group-invite-dialog.tsx
- apps/hub/src/lib/create-schema-form.tsx
> fix: allow creating an invite without touching a form

- apps/hub/src/domains/group/components/dialogs/create-group-invite-dialog.tsx
- apps/hub/src/domains/group/views/group-games.tsx
- apps/hub/src/routes/__root.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/backend/index.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/backend/logs.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/backend/variables.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/lobbies/index.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/lobbies/logs.tsx
- apps/hub/src/routes/_authenticated/_layout/index.tsx
- apps/hub/src/routes/_authenticated/_layout/teams/$groupId.tsx
- apps/hub/src/routes/_authenticated/_layout/teams/$groupId/index.tsx
- apps/hub/src/routes/_authenticated/devices.link.$token.tsx
- apps/hub/src/routes/_authenticated/invite.$inviteCode.tsx
> fix: throw not found directly in route

- apps/hub/src/components/auth-card.tsx
- apps/hub/src/domains/auth/forms/login-form.tsx
- apps/hub/src/domains/auth/views/login-view/email-step.tsx
- apps/hub/src/queries/global.ts
Closes RVTEE-524
Closes HUB-483
> fix: auth issues

- apps/hub/src/queries/global.ts
> fix: refresh token when it gets outdated

- apps/hub/src/domains/game/components/dialogs/create-dynamic-server-dialog.tsx
- apps/hub/src/domains/game/components/game-matchmaker/lobby-region.tsx
- apps/hub/src/domains/game/components/game-servers/game-server-build-select.tsx
- apps/hub/src/domains/game/components/game-servers/game-server-datacenter-select.tsx
- apps/hub/src/domains/game/components/game-servers/game-server-datacenter.tsx
- apps/hub/src/domains/game/components/game-servers/game-server-network-mode-select.tsx
- apps/hub/src/domains/game/components/game-servers/game-server-network-protocol-select.tsx
- apps/hub/src/domains/game/components/game-servers/game-server-network-tab.tsx
- apps/hub/src/domains/game/components/game-servers/game-server-runtime-tab.tsx
- apps/hub/src/domains/game/components/game-servers/game-server-tags.tsx
- apps/hub/src/domains/game/components/game-servers/game-servers-list-panel.tsx
- apps/hub/src/domains/game/forms/create-dynamic-server-form.tsx
- apps/hub/src/domains/game/queries/dynamic-servers/mutations.ts
- apps/hub/src/domains/game/queries/dynamic-servers/query-options.ts
- apps/hub/src/hooks/use-dialog.tsx
- apps/hub/src/hooks/use-feature-flag.ts
- apps/hub/src/lib/utils.ts
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/servers/builds.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/servers/index.tsx
- apps/hub/tailwind.config.js
- packages/components/src/ui/dialog.tsx
- packages/components/src/ui/form.tsx
- packages/components/src/value-card.tsx
Closes RVTEE-499
Closes HUB-477
Closes HUB-476
https://github.com/user-attachments/assets/0c736b2a-a2f8-4176-97cb-b4e267180227
> feat: ds creation, servers datacenter bagde, ux improvements

- apps/hub/src/domains/game/components/game-backend/game-backend-response-badge.tsx
- apps/hub/src/domains/game/queries/backend/types.ts
> feat: display timeouts in backend logs

- apps/hub/src/domains/game/queries/dynamic-servers/mutations.ts
> fix: invalidate servers cache when destroying a server

- apps/hub/src/domains/game/queries/backend/types.ts
> refactor: show only POST requests as backend calls

- apps/hub/src/components/error-component.tsx
- apps/hub/src/components/header/links/header-namespace-links.tsx
- apps/hub/src/domains/game/queries/query-options.tsx
- apps/hub/src/hooks/use-feature-flag.ts
- apps/hub/src/routeTree.gen.ts
- apps/hub/src/routes/_authenticated/_layout/games/$gameId/namespaces/$.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId/settings/index.tsx
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/index.tsx
Closes RVTEE-500
Closes HUB-490
> feat: prepare for metadata api

- apps/hub/package.json
- apps/hub/src/domains/game/components/game-backend/game-backend-event-details/game-backend-event-details-logs-tab.tsx
- apps/hub/src/domains/game/components/game-servers/game-server-logs-tab.tsx
- yarn.lock
> feat: add option to export logs

- apps/hub/src/components/command-panel/command-panel-page/namespace-command-panel-page.tsx
- apps/hub/src/components/header/links/header-namespace-links.tsx
- apps/hub/src/domains/game/queries/query-options.tsx
- apps/hub/src/domains/user/layouts/profile-layout.tsx
- apps/hub/src/hooks/use-feature-flag.ts
- apps/hub/src/routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/index.tsx
> feat: always enable backend, enable mm only on certain constraints

- packages/components/src/ui/badge.tsx
> fix: invalid layout in server status badge
